Repository liesel-devs/liesel, pull requests merged in 2023-03, with the labels that each got.

#40 Spike and Slab tutorial with PyMC
  docs/source/tutorials/qmd/06-pymc.qmd
Labels: comp:tutorials, comp:experimental

#39 Fix test coverage calculation
  .github/workflows/pytest.yml
Labels: bug

#47 Improve mvn docs
  docs/source/_templates/autosummary/class-without-inheritance-strict.rst
  liesel/distributions/mvn_degen.py
Labels: comp:documentation

#49 Adds a method to convert sampling results to arviz's inference data
  conftest.py
  liesel/experimental/arviz.py
  setup.cfg
  tests/__init__.py
  tests/conftest.py
  tests/experimental/__init__.py
  tests/experimental/test_conversion_to_arviz.py
  tests/goose/test_summary_m.py
  tests/mock_kernel.py
Labels: comp:goose

#48 Improve docstrings for Node and Var, closes #43
  liesel/model/nodes.py
Labels: comp:documentation

#57 Use () instead of <> in __repr__
  liesel/model/model.py
  liesel/model/nodes.py
  tests/model/test_graph_builder.py
Labels: bug, comp:model

#60 Pin pydata-sphinx-theme version to fix docs
  docs/source/conf.py
  setup.cfg
Labels: bug, comp:documentation

#63 Add groups tutorial
  docs/source/tutorials/qmd/07-groups.qmd
  docs/source/tutorials_overview.rst
Labels: comp:documentation
