Repository liesel-devs/liesel, pull requests merged in 2023-11, with the labels that each got.

#109 Fix #103
  CHANGELOG.md
  liesel/goose/summary_m.py
Labels: comp:goose

#137 Make error_df public (closes #94)
  CHANGELOG.md
  liesel/goose/summary_m.py
Labels: enhancement, comp:goose

#136 Refactor goose-models to goose-interfaces (closes #110)
  .github/README-files/goose-plot-1.png
  .github/README.md
  .github/README.qmd
  CHANGELOG.md
  docs/source/tutorials/qmd/01-lin-reg.qmd
  docs/source/tutorials/qmd/01a-transform.qmd
  docs/source/tutorials/qmd/02-ls-reg.qmd
  docs/source/tutorials/qmd/04-mcycle.qmd
  liesel/goose/__init__.py
  liesel/goose/interface.py
  liesel/goose/models.py
  liesel/model/distreg.py
  liesel/model/goose.py
  tests/conftest.py
  tests/distributions/test_mvn_degen.py
  tests/goose/files/for_test_summary.py
  tests/goose/kernels/model_lm.py
  tests/goose/test_builder.py
  tests/goose/test_deterministic_kernels.py
  tests/goose/test_engine.py
  tests/goose/test_interface_dataclass.py
  tests/goose/test_interface_dict.py
  tests/goose/test_interface_liesel.py
  tests/goose/test_kernel_sequence.py
  tests/model/test_distreg.py
Labels: enhancement, comp:goose, comp:model

#133 MVN Degenerate from smoothing param
  liesel/distributions/mvn_degen.py
  tests/distributions/test_mvn_degen.py
Labels: enhancement, comp:tfp

#143 Improve node documentation
  .github/workflows/docs.yml
  liesel/model/model.py
  liesel/model/nodes.py
Labels: comp:documentation

#144 Jittering Functions documentation
  liesel/goose/builder.py
  liesel/model/distreg.py
Labels: comp:documentation

#140 Make GEV tutorials to work
  docs/source/tutorials/qmd/03-gev.qmd
  liesel/goose/types.py
  liesel/model/distreg.py
Labels: bug, comp:documentation

#149 Update linreg and distreg tutorials
  docs/source/tutorials/qmd/01-lin-reg.qmd
  docs/source/tutorials/qmd/01a-transform.qmd
  docs/source/tutorials/qmd/02-ls-reg.qmd
Labels: comp:documentation

#156 Allow passing key as seed
  liesel/goose/builder.py
  tests/goose/test_builder.py
Labels: enhancement, comp:goose, good first issue
